exp_name: "1"

# ==== Resume training ==== #
resume: false
last_epoch: 0
# ==== Resume training ==== #

model: "FourConv"
batch_size: 64
test_size: 64
max_epoch: 30
lr: 0.0001
decay_steps: [10, 20]
gamma: 0.5

new_size: 128
weighted: false

data_root: "./datasets/"
save_root: "./runs/"